theme = "Coder"
baseURL = "https://github.com/vert0x9/my-site"
languageCode = "en-us"
title = "Max Savenko"

[params]
  avatarURL = "images/avatar.jpg"
  darkColorScheme = true

[params.social]
  name = "GitHub"
  icon = "fa-brands fa-github"
  url = "https://github.com/vert0x9"
  weight = 1
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2